version: '3.4'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - ./postgres_data:/var/lib/postgresql:rw
        - ./deployments:/opt/jboss/wildfly/standalone/deployments:rw
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: ch@ng3M3!
      ports:
        - 5432:5432
  keycloak:
      image: jboss/keycloak
      environment:
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: ch@ng3M3!
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: ch@ng3M3!
      ports:
        - 8080:8080
        - 9990:9990
      depends_on:
        - postgres
  web:
    build: .
    command: npm run
    volumes:
      - ./app:/usr/app/
      - ./app/node_modules:/usr/app/node_modules
    ports:
      - 3000:3000
